//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeiboCollector.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Collector : global::System.Configuration.ApplicationSettingsBase {
        
        private static Collector defaultInstance = ((Collector)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Collector())));
        
        public static Collector Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("../_Data/Pictures/")]
        public string picPath {
            get {
                return ((string)(this["picPath"]));
            }
            set {
                this["picPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("../_Data/Weibo/")]
        public string weiboPath {
            get {
                return ((string)(this["weiboPath"]));
            }
            set {
                this["weiboPath"] = value;
            }
        }
    }
}
